language: c++

branches:
  except:
    - automatic

cache:
  directories:
    - download

matrix:
  include:
    - os: osx
      sudo: required
      env:
        - _BUILD=macos
      before_install:
        - source .travis/macports-ci install
      install:
        - sudo port -v install cairo
      script:
        - bash .travis/script-macos.sh
        - cp -av bin stone-phaser-"$_BUILD"
        - rm -f stone-phaser-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/stone-phaser-"$_BUILD".zip stone-phaser-"$_BUILD"

before_script:
  - sed -i~ 's%/usr/local%/usr%g' plugins/*/Makefile
  - patch -d dpf -p1 -i "`pwd`"/resources/patch/DPF-bypass.patch

before_deploy:
  - |
    if test "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false"; then
      export TRAVIS_TAG=automatic
      git tag -f "$TRAVIS_TAG"
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: release/*
  file_glob: true
  skip_cleanup: true
  prerelease: true
  overwrite: true
  on:
    branch: master

env:
  global:
    secure: Zm4zN4XCJ7dWilM0kS5aze4xiwTPjGXJaGTq9xJ5ohFWyiwwJQCd+DgYlzaHSDgnGprpK8jCx09Ew3R/1LsRG5FAxwZEAqXHe3iKqRWDg8D+JArDBJU6dOlY0sjKbz4KYpY4qRwEY4h1MpHHOWI3Q1UbSMzkSFWIbfmbVFwwUj7A4O5hy4RByZHZPPkbUoIQEjBR4iG+W5tS5vyMPB7XdSdR0I+ogYuEx1HYSTEZZjITvEg3+G388QYKPan+ubZiw699UeWOPWR1HB8fXES0XZZ5b9gzFWya8V2EhLWhaAq29qM2yyG4d0N2Iy/nwhJCgImhiGRybSgy7MLfhqKHi9rfnZ7ebRcMtR2wLrzBdC2u72NuzsbkCAqQisTCgq2rmk+uXF6zwAPn52h7In0uox9kAFoxmp/oGNZYXnvsw+2uzyRIdzfym/fpQpfVryVpNr/ffMmUbjs47GSMBJx4jBi+aoj9uRsUGlod5ugXHKwiayz2Qy97IhWJIEC5Z/EMP/50jintyDC0VwXAj2ZWA5mTm8/WOYMj39mSTPu+kkFJ6/U1SaQOACIPLcj2OxID430B9TNdTXXWTH0H01rTxgT062Kn9ouuPnBXk/xGIDBjZqXf/lLSW8bLYJKcF5yffLAov536JXRmNDYLBqUQOtXgBOzH8lq9+AHfhx3Hlro=
