language: c++

branches:
  except:
    - automatic

cache:
  directories:
    - download

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      env:
        - _BUILD=win32
        - _MINGW=mingw32
        - _HOST=i686-w64-mingw32
      before_install:
        - sudo add-apt-repository ppa:kxstudio-debian/kxstudio -y
        - sudo add-apt-repository ppa:kxstudio-debian/mingw -y
        - sudo add-apt-repository ppa:kxstudio-debian/toolchain -y
        - sudo apt-get update -qq
        - sudo apt-get install kxstudio-repos
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -y g++ pkg-config "${_MINGW}"-x-gcc "${_MINGW}"-x-pkgconfig wine
      script:
        - bash .travis/script-mingw.sh
        - cp -drfv bin stone-phaser-"$_BUILD"
        - rm -f stone-phaser-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/stone-phaser-"$_BUILD".zip stone-phaser-"$_BUILD"
    - os: linux
      sudo: required
      dist: trusty
      env:
        - _BUILD=win64
        - _MINGW=mingw64
        - _HOST=x86_64-w64-mingw32
      before_install:
        - sudo add-apt-repository ppa:kxstudio-debian/kxstudio -y
        - sudo add-apt-repository ppa:kxstudio-debian/mingw -y
        - sudo add-apt-repository ppa:kxstudio-debian/toolchain -y
        - sudo apt-get update -qq
        - sudo apt-get install kxstudio-repos
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -y g++ pkg-config "${_MINGW}"-x-gcc "${_MINGW}"-x-pkgconfig wine
      script:
        - bash .travis/script-mingw.sh
        - cp -drfv bin stone-phaser-"$_BUILD"
        - rm -f stone-phaser-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/stone-phaser-"$_BUILD".zip stone-phaser-"$_BUILD"
    - os: osx
      sudo: required
      env:
        - _BUILD=macos
      script:
        - bash .travis/script-macos.sh
        - cp -av bin stone-phaser-"$_BUILD"
        - rm -f stone-phaser-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/stone-phaser-"$_BUILD".zip stone-phaser-"$_BUILD"
    - os: linux
      sudo: required
      dist: trusty
      env:
        - _BITS=64
        - _BUILD=linux64
      before_install:
        - sudo apt-get update -qq
      install:
        - # sudo apt-get install
      script:
        - bash .travis/script-linux.sh
        - cp -drfv bin stone-phaser-"$_BUILD"
        - rm -f stone-phaser-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/stone-phaser-"$_BUILD".zip stone-phaser-"$_BUILD"
    - os: linux
      sudo: required
      dist: trusty
      env:
        - _BITS=32
        - _BUILD=linux32
      before_install:
        - sudo dpkg --add-architecture i386
        - sudo apt-get update -qq
      install:
        - sudo apt-get install libc6-dev-i386 lib32stdc++-4.8-dev libc6:i386 libstdc++6:i386
      script:
        - bash .travis/script-linux.sh
        - cp -drfv bin stone-phaser-"$_BUILD"
        - rm -f stone-phaser-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/stone-phaser-"$_BUILD".zip stone-phaser-"$_BUILD"
