name: build

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]*'
      - 'v[0-9]*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: win32
            display-name: Windows 32-bit
            runs-on: windows-2022
            platform: x86
            release-arch: Win32
            os-type: Windows
            build-type: Release
            vcpkg-triplet: x86-windows-static
            vcpkg-commit-id: 5afd32266c257e8cdd8e1c272bdf8964e37dd501
          - name: win64
            display-name: Windows 64-bit
            runs-on: windows-2022
            platform: x64
            release-arch: x64
            os-type: Windows
            build-type: Release
            vcpkg-triplet: x64-windows-static
            vcpkg-commit-id: 5afd32266c257e8cdd8e1c272bdf8964e37dd501
          - name: linux64
            display-name: Linux 64-bit
            runs-on: ubuntu-20.04
            platform: x64
            release-arch: Linux64
            os-type: Linux
            build-type: Release
      fail-fast: false
    name: Compile for ${{ matrix.display-name }}
    runs-on: ${{ matrix.runs-on }}
    env:
      name: ${{ matrix.name }}
      display_name: ${{ matrix.display-name }}
      platform: ${{ matrix.platform }}
      release_arch: ${{ matrix.release-arch }}
      build_type: ${{ matrix.build-type }}
      num_jobs: 2
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.vcpkg-triplet }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Apply patches
        run: |
          patch -p0 -i resources/patches/dpf-cairo-h.patch
          patch -p0 -i resources/patches/dpf-static.patch
      - name: Install dependencies (Linux)
        if: ${{ matrix.os-type == 'Linux' }}
        run: sudo apt-get -y install libcairo2-dev
      - name: Install dependencies (Windows)
        if: ${{ matrix.os-type == 'Windows' }}
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: ${{ matrix.vcpkg-commit-id }}
          #runVcpkgInstall: true
      - name: Create Build Directory
        working-directory: ${{ runner.workspace }}
        run: cmake -E make_directory build
      - name: Configure CMake (Windows)
        if: ${{ matrix.os-type == 'Windows' }}
        working-directory: ${{ runner.workspace }}/build
        run: cmake "${Env:GITHUB_WORKSPACE}" -G"Visual Studio 17 2022" -A"${Env:release_arch}" -DCMAKE_BUILD_TYPE="${Env:build_type}" -DCMAKE_CXX_STANDARD=17 -DCMAKE_TOOLCHAIN_FILE="${Env:RUNVCPKG_VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
      - name: Configure CMake (Linux)
        if: ${{ matrix.os-type == 'Linux' }}
        working-directory: ${{ runner.workspace }}/build
        run: cmake "${GITHUB_WORKSPACE}" -DCMAKE_BUILD_TYPE="${build_type}" -DCMAKE_CXX_STANDARD=17
      - name: Print vcpkg logs
        if: ${{ matrix.os-type == 'Windows' && failure() }}
        working-directory: ${{ runner.workspace }}/build
        run: If (Test-Path -PathType Leaf vcpkg-manifest-install.log) { Get-Content vcpkg-manifest-install.log }
      - name: Build (Windows)
        if: ${{ matrix.os-type == 'Windows' }}
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --config "${Env:build_type}" -j "${Env:num_jobs}"
      - name: Build (Linux)
        if: ${{ matrix.os-type == 'Linux' }}
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --config "${build_type}" -j "${num_jobs}"
      - uses: actions/upload-artifact@v2
        with:
          name: Stone Phaser for ${{ matrix.display-name }}
          path: "${{runner.workspace}}/build/bin/*"
